version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ecomm-app-nestjs
    restart: always
    environment:
      POSTGRES_USER: abhishek
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: bazarapi
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
